name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run
        run: cd test && docker compose up --build -d
      - run: sleep 10
      - name: Test
        run: cd test && docker compose exec lurch hurl  --test --glob '/etc/lurch/test/**/*.hurl'


